test:
  image: yourlabs/ansible
  script:
  - ANSIBLE_HOST_KEY_CHECKING=False
    bigsudo
    .
    root@target
    ansible_ssh_pass=root
    -v
  services:
  - name: docker.io/yourlabs/sshd:ubuntu1804
    alias: target
