test:
  image: yourlabs/ansible

  script:
  - ANSIBLE_HOST_KEY_CHECKING=False
    bigsudo
    .
    root@target
    ansible_ssh_pass=root
    -vv | tee -a out
  - grep 'unreachable=0.*failed=0' out

  services:
  - name: docker.io/yourlabs/sshd:ubuntu1804
    alias: target
