---

- name: Set facts for CentOS
  when: ansible_os_family == 'RedHat'
  set_fact:
    firewall_rules_path: /etc/sysconfig/iptables
    firewall_packages: iptables
    firewall_service: iptables
    service_manager: systemctl

- name: Set facts for Arch
  when: ansible_os_family == 'Archlinux'
  set_fact:
    firewall_rules_path: /etc/iptables/iptables.rules
    firewall_packages: iptables
    firewall_service: iptables
    service_manager: systemctl

- name: Set facts for Debian
  when: ansible_os_family == 'Debian'
  set_fact:
    firewall_rules_path: /etc/iptables/rules.v4
    firewall_packages: iptables,iptables-persistent
    firewall_service: netfilter-persistent
    service_manager: systemctl

- name: Set facts for Alpine
  when: ansible_os_family == 'Alpine'
  set_fact:
    firewall_rules_path: /etc/iptables/iptables.rules
    firewall_packages: iptables
    firewall_service: iptables
    service_manager: rc-service

- name: Create /etc/iptables
  file:
    path: /etc/iptables
    state: directory

- name: Install iptables configuration
  notify: Apply firewall
  when: rules|default('')
  copy:
    backup: yes
    dest: '{{ firewall_rules_path }}'
    owner: root
    group: root
    mode: 644
    content: '{{ rules }}'

- name: Install iptables
  package: name={{ firewall_packages }}

- name: /etc/systemd/system/iptables.service.d
  file:
    path: /etc/systemd/system/{{ firewall_service }}.service.d
    state: directory
