---

- name: Apply firewall
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart iptables
  notify: '{{ notify|default(false) }}'
  service:
    name: '{{ firewall_service }}'
    state: restarted
    enabled: yes
