---

- name: Apply firewall
  notify: Restart docker
  shell: systemctl daemon-reload

- name: Restart iptables
  notify: '{{ notify|default(false) }}'
  service:
    name: '{{ firewall_service }}'
    state: restarted
    enabled: yes
