---

- name: Apply firewall
  shell: sh -c "type systemctl && systemctl daemon-reload || echo systemctl skip"

- name: Restart iptables
  notify: '{{ notify|default(false) }}'
  service:
    name: '{{ firewall_service }}'
    state: restarted
    enabled: yes
